import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => (
  <header>
    <div className="text-center bg-purple-600 p-2 my-1 rounded-md">
      <Link href="/">
        <h1 className="text-2xl text-white font-bold my-1">My Blog</h1>
      </Link>
    </div>
  </header>
);

const Footer = () => (
  <footer>
    <div className="border-t border-slate-400 mt-4 py-6 text-center text-slate-400">
      <h3>Awesome blog</h3>
    </div>
  </footer>
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="mx-auto  max-w-2xl px-6">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
